// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: check_refreshtoken.sql

package database

import (
	"context"
)

const getTokenData = `-- name: GetTokenData :one
SELECT token, created_at, updated_at, user_id, expires_at, revoked_at
FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) GetTokenData(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getTokenData, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
