// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: refresh_jwt.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const refreshJWT = `-- name: RefreshJWT :exec
UPDATE refresh_tokens
SET token = $1
WHERE user_id = $2
`

type RefreshJWTParams struct {
	Token  string
	UserID uuid.NullUUID
}

func (q *Queries) RefreshJWT(ctx context.Context, arg RefreshJWTParams) error {
	_, err := q.db.ExecContext(ctx, refreshJWT, arg.Token, arg.UserID)
	return err
}
