// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update_password.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET hashed_password = $1
WHERE id = $2
`

type UpdatePasswordParams struct {
	HashedPassword string
	ID             uuid.UUID
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.HashedPassword, arg.ID)
	return err
}
