// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update_email.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateEmail = `-- name: UpdateEmail :exec
UPDATE users
SET email = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateEmailParams struct {
	Email string
	ID    uuid.UUID
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateEmail, arg.Email, arg.ID)
	return err
}
