// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: upgrade_to_red.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const upgradeToRed = `-- name: UpgradeToRed :exec
UPDATE users
SET is_chirpy_red = true, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpgradeToRed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, upgradeToRed, id)
	return err
}
